// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_H4JeH_IMt3iNoU3dlJLutK1YmFYTSlc',
    appId: '1:384985207660:web:5feb72ca7ca886d218d949',
    messagingSenderId: '384985207660',
    projectId: 'test-app-4bbd6',
    authDomain: 'test-app-4bbd6.firebaseapp.com',
    storageBucket: 'test-app-4bbd6.firebasestorage.app',
    measurementId: 'G-P22KJPTSS2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlS0Lk9t2VdX-ceVe9LinMMDYyWSQKeyU',
    appId: '1:384985207660:android:032428658e3b6ff018d949',
    messagingSenderId: '384985207660',
    projectId: 'test-app-4bbd6',
    storageBucket: 'test-app-4bbd6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPYlZ6hTBiTly9helPra9OR5hf1PqQ-rk',
    appId: '1:384985207660:ios:929fac3924c1bc2018d949',
    messagingSenderId: '384985207660',
    projectId: 'test-app-4bbd6',
    storageBucket: 'test-app-4bbd6.firebasestorage.app',
    iosClientId: '384985207660-flhf50ar7lrcqr82i9bd6gom8ht18egs.apps.googleusercontent.com',
    iosBundleId: 'com.example.caffeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPYlZ6hTBiTly9helPra9OR5hf1PqQ-rk',
    appId: '1:384985207660:ios:929fac3924c1bc2018d949',
    messagingSenderId: '384985207660',
    projectId: 'test-app-4bbd6',
    storageBucket: 'test-app-4bbd6.firebasestorage.app',
    iosClientId: '384985207660-flhf50ar7lrcqr82i9bd6gom8ht18egs.apps.googleusercontent.com',
    iosBundleId: 'com.example.caffeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_H4JeH_IMt3iNoU3dlJLutK1YmFYTSlc',
    appId: '1:384985207660:web:79b5f3a4b4b2975c18d949',
    messagingSenderId: '384985207660',
    projectId: 'test-app-4bbd6',
    authDomain: 'test-app-4bbd6.firebaseapp.com',
    storageBucket: 'test-app-4bbd6.firebasestorage.app',
    measurementId: 'G-W7BS7XXCN2',
  );
}
